export {default as instagramIcon} from "./3instagram.svg"
export {default as LinkedInIcon} from "./skill-icons_linkedin.svg"
export {default as twitterIcon} from "./Vectortwitter.svg"
export {default as facebookIcon} from "./Vectorfacebook.svg"
export {default as sendnaw_logo} from "./sendnawlogo.svg"
export {default as emailIcon} from "./clarity_envelope-line.svg"
export {default as icon1} from "./Group 20900.png"
export {default as icon2} from "./Group 20904.png"
export {default as icon3} from "./Group 20905.png"
export {default as icon4} from "./Group 20902.png"
export {default as icon6} from "./Group 20909.png"
export {default as a1} from "./Group 20909 (1).png"
export {default as a2} from "./Group 20911.png"
export {default as vector} from "./Vector (1).png"
export {default as img} from "./Group 20895.svg"
export {default as line_1} from "./Line 1.svg"
export {default as quote} from "./entypo_quote.svg"
export {default as left_arrow} from "./ph_arrow-up-thin-orange.svg"
export {default as right_arrow} from "./ph_arrow-up-thin.svg"
export {default as party_hat_1} from "./party-hat-1.svg"
export {default as party_hat_2} from "./party-hat-2.svg"
export {default as heroimage} from "./image 2.png"
export {default as line} from "./Ornamen.png"
export {default as appstore} from "./appstore.png"
export {default as google} from "./googleplay.png"
export {default as abstract} from "./abstract_003.png"
export {default as molecular} from "./molecular_019.png"
export {default as up_arrow} from "./ep_arrow-up.svg"
export {default as down_arrow} from "./ep_arrow-down.svg"